<#1>
<?php
\srag\Plugins\SrUserEnrolment\Repository::getInstance()->installTables();
?>
<#2>
<?php
\srag\Plugins\SrUserEnrolment\Repository::getInstance()->installTables();
?>
<#3>
<?php
\srag\Plugins\SrUserEnrolment\Repository::getInstance()->installTables();
?>
